[package]
name = "full"
version = "0.1.0"
description = "Matrix and array types for numeric values"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
num-complex = "0.4"
opimps = "0.1"
rand = "0.8"
rand_distr = "0.4"
